"""Public Bazel rules for working with GitLab CI configuration.

Today (v0.1.0):

  * `gitlab_ci_validate(name, src)` — build-action rule. Validates
    a `.gitlab-ci.yml` against the official GitLab JSON Schema
    pinned by sha via the `gitlab_schemas` module extension.
    Hermetic; no network, no auth.
  * `gitlab_ci_lint(name, src, host, repo)` — `bazel run`-able
    target. Wraps `glab ci lint <src>` via the `glab` toolchain.
    Hits the GitLab API for full pipeline validation (semantic
    checks beyond pure schema + `include:` resolution). Requires
    `glab auth login` to the target instance.

Future surface:

  * `gitlab_ci_lint_remote(name, src, project)` — call
    `/api/v4/projects/:id/ci/lint` directly (no glab CLI
    indirection), bake the project context.
  * Deploy + registry helpers, schema-derived typed Starlark rules
    for authoring `.gitlab-ci.yml` from Bazel (mirroring the
    rules_jsonschema + rules_cloudformation pattern).

Limitations of `gitlab_ci_validate`:

  * Does not follow `include:` directives. A `.gitlab-ci.yml`
    that imports another project's snippets is validated only at
    its own leaf level; chain validations on the included files
    by registering each as a separate `gitlab_ci_validate`
    target. `gitlab_ci_lint` handles includes server-side.
"""

load("//gitlab/glab:toolchain_type.bzl", "GLAB_TOOLCHAIN_TYPE")

def _gitlab_ci_validate_impl(ctx):
    stamp = ctx.actions.declare_file(ctx.label.name + ".ok")
    schema = ctx.file._schema
    src = ctx.file.src
    args = ctx.actions.args()
    args.add("--schema", schema.path)
    args.add("--src", src.path)
    args.add("--stamp", stamp.path)
    ctx.actions.run(
        executable = ctx.executable._validator,
        arguments = [args],
        inputs = [schema, src],
        outputs = [stamp],
        mnemonic = "GitlabCiValidate",
        progress_message = "Validating .gitlab-ci.yml against pinned GitLab schema (%s)" % ctx.label,
    )
    return [DefaultInfo(files = depset([stamp]))]

gitlab_ci_validate = rule(
    implementation = _gitlab_ci_validate_impl,
    doc = "Validate a `.gitlab-ci.yml` against the official GitLab JSON Schema (pinned by sha256 via the `gitlab_schemas` module extension). Output: a stamp file Bazel checks for caching; on schema violation the build fails with check-jsonschema's diagnostic on stderr.",
    attrs = {
        "src": attr.label(
            mandatory = True,
            allow_single_file = [".yml", ".yaml"],
            doc = "Label of the `.gitlab-ci.yml` (or sibling fragment) to validate.",
        ),
        "_schema": attr.label(
            default = "@gitlab_ci_schema//file:gitlab-ci.schema.json",
            allow_single_file = True,
        ),
        "_validator": attr.label(
            default = "//gitlab/private:validate",
            executable = True,
            cfg = "exec",
        ),
    },
)

_LINT_TEMPLATE = """#!/usr/bin/env bash
# @generated by gitlab_ci_lint. DO NOT EDIT — re-run \\`bazel build\\` to refresh.
set -euo pipefail

# Locate runfiles. Under `bazel run`, $RUNFILES_DIR is set;
# standalone invocations get `$0.runfiles`.
if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
    if [[ -d "$0.runfiles" ]]; then
        RUNFILES_DIR="$0.runfiles"
    elif [[ -d "${{BASH_SOURCE[0]}}.runfiles" ]]; then
        RUNFILES_DIR="${{BASH_SOURCE[0]}}.runfiles"
    else
        echo "gitlab_ci_lint: cannot locate runfiles directory" >&2
        exit 1
    fi
fi

GLAB_BIN="$RUNFILES_DIR/{glab_runfile}"
SRC="$RUNFILES_DIR/{src_runfile}"

if [[ ! -x "$GLAB_BIN" ]]; then
    echo "gitlab_ci_lint: glab toolchain binary not found at $GLAB_BIN" >&2
    exit 1
fi
if [[ ! -f "$SRC" ]]; then
    echo "gitlab_ci_lint: source not found at $SRC" >&2
    exit 1
fi

# glab uses the current working directory's git remote to choose
# which GitLab instance to talk to. Under `bazel run` the cwd is
# the workspace root, which may or may not be a gitlab repo; pass
# {repo_or_host_args} explicitly to remove the ambiguity.
echo "gitlab_ci_lint: linting $SRC{repo_or_host_log}" >&2

exec "$GLAB_BIN" ci lint{repo_or_host_args} "$SRC" "$@"
"""

def _runfile_path(ctx, f):
    if f.short_path[:3] == "../":
        return f.short_path[3:]
    return ctx.workspace_name + "/" + f.short_path

def _gitlab_ci_lint_impl(ctx):
    glab_info = ctx.toolchains[GLAB_TOOLCHAIN_TYPE].glab_info
    glab_exec = glab_info.glab.executable
    src = ctx.file.src

    # Compose glab flags from the user-set host/repo. Either can be
    # blank — in that case glab falls back to git-remote detection
    # (likely irrelevant in the Bazel sandbox), so we strongly
    # recommend setting at least `repo`.
    repo_arg = ""
    log_suffix = ""
    if ctx.attr.repo:
        repo_arg = " -R " + ctx.attr.repo
        log_suffix = " (repo=" + ctx.attr.repo + ")"
    elif ctx.attr.host:
        # `-R` accepts a full URL; use the host attr to assemble a
        # placeholder url that anchors the gitlab instance even
        # when the project path isn't known.
        repo_arg = " -R https://" + ctx.attr.host
        log_suffix = " (host=" + ctx.attr.host + ")"

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        launcher,
        _LINT_TEMPLATE.format(
            glab_runfile = _runfile_path(ctx, glab_exec),
            src_runfile = _runfile_path(ctx, src),
            repo_or_host_args = repo_arg,
            repo_or_host_log = log_suffix,
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [src, glab_exec]).merge(
        glab_info.default_runfiles,
    )
    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

gitlab_ci_lint = rule(
    implementation = _gitlab_ci_lint_impl,
    executable = True,
    doc = "`bazel run`-able target that lints a `.gitlab-ci.yml` via `glab ci lint`. Network-bound: hits the GitLab API, requires the user to be `glab auth login`-ed to the target instance. For hermetic schema-only validation, use `gitlab_ci_validate` instead.",
    attrs = {
        "src": attr.label(
            mandatory = True,
            allow_single_file = [".yml", ".yaml"],
            doc = "Label of the `.gitlab-ci.yml` (or fragment) to lint.",
        ),
        "host": attr.string(
            doc = "GitLab host (e.g. `gitlab.savvifi.com`). " +
                  "Used to anchor `glab`'s API target when the " +
                  "runfiles cwd doesn't have a gitlab remote. " +
                  "Ignored if `repo` is set (which carries host).",
        ),
        "repo": attr.string(
            doc = "`OWNER/REPO` or full URL passed as `glab -R`. " +
                  "Strongly recommended — lets `glab` pick the right " +
                  "GitLab instance + project context without inspecting " +
                  "the sandbox's git state.",
        ),
    },
    toolchains = [GLAB_TOOLCHAIN_TYPE],
)
